name = "web-tools"
compatibility_date = "2022-02-01"
main = "./dist/worker.js"


account_id = "7c013056add27d48fba6bac18fecd661"
workers_dev = true

kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "5f6a6d76b57846549ccddefa84ef63e0" }
]

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-dev"

[site]
bucket = "./public"

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[env.production]
# route = "jsonhero.io/*"
zone_id = "af3c12add61e94b88b3d2cbfb6f65782"
kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "5f6a6d76b57846549ccddefa84ef63e0" }
]

[env.production.vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"

# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [APIHERO_PROJECT_KEY]
